### ISSUE TITLE
Port forward hook doesn't run

### ISSUE THREAD

**Issue by AnonymousX86** [triffid/pia-wg#13]
I've added this to `/etc/pia-wg/pia-wg.conf` (as I'm running `sudo ./pia-wg.sh`):
```sh
PORTFORWARD_HOOK="/bin/bash -c '/etc/pia-wg/run-app.sh $PF_PORT'"
```
That script runs a Docker image and attaches the container to PIA. Script itself works when run:
```sh
PF_PORT=12345
/bin/bash -c "/etc/pia-wg/run-app.sh $PF_PORT"
```
After running `sudo ./pia-wg.sh` I'm getting information that I can add custom hook:
```plaintext
You could provide a portforward hook in your pia-wg.conf to automatically feed the bound port to some other program or system
To do so, add:
    portforward_hook() { my_program 12345; }
or similar to /home/user/pia-wg/pia-config.sh
Note: pia-portforward.sh should be called every ~5 minutes to maintain your forward.
You could try:
    while sleep 5m; do pia-portforward.sh; done
or alternately add a cronjob with crontab -e
```
Even adding something like this:
```sh
PORTFORWARD_HOOK="echo TEST $PF_PORT"
```
Doesn't do anything.

Am I missing something?

**Comment by triffid** [comment]
You're supplying a variable, while the script is looking for a [bash function](https://www.gnu.org/software/bash/manual/html_node/Shell-Functions.html).

`PORTFORWARD_HOOK="echo TEST $PF_PORT"` is entirely different to `portforward_hook() { echo TEST $PF_PORT; }`

See https://github.com/triffid/pia-wg/blob/master/pia-portforward.sh#L115 and note that `type -t «blah»` returns retcode=1 and empty string for variable names.
