### ISSUE TITLE
Specific Server

### ISSUE THREAD

**Issue by SamB-GB** [triffid/pia-wg#9]
Is there a way for me to generate the Wireguard Config for a specific server instead of auto selecting a server?

**Comment by triffid** [comment]
You can specify `LOC="pattern"` in the config to force a specific locale.

If you specify a `LOC` that matches nothing, it'll spit out a list of available locales - or you can just check the `id` fields in https://serverlist.piaservers.net/vpninfo/servers/v6 yourself.

Note that it'll match any location that _starts with_ the pattern you specify, so `LOC="us"` will match _any_ us-based server, but specifying `LOC="us_denver"` will _only_ use the `us_denver` endpoint(s)

See https://github.com/triffid/pia-wg/blob/master/pia-wg.sh#L197-L214

If a region has multiple IP addresses and you want to use a specific one, it's a bit trickier - you can try editing the cached server info ( https://github.com/triffid/pia-wg/blob/master/pia-config.sh#L95-L103 ) and tell it to reconnect ( https://github.com/triffid/pia-wg/blob/master/pia-wg.sh#L44 )
